services:
  todolist.api:
    image: todolist.api
    build:
      context: .
      dockerfile: src/TodoList.API/Dockerfile
    ports:
      - "5001:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Server=${DB_HOST};Database=${DB_NAME};Uid=${DB_USER};Pwd=${DB_PASSWORD};
    depends_on:
      - db
  db:
    image: mysql:lts
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - todolist_db:/var/lib/mysql

volumes:
  todolist_db:
